// Code generated by "stringer -type=suggestLevel util.go"; DO NOT EDIT.

package dns

import "strconv"

const _suggestLevel_name = "DISABLEBLOCKSPEEDUPlevelEnd"

var _suggestLevel_index = [...]uint8{0, 7, 12, 19, 27}

func (i suggestLevel) String() string {
	if i < 0 || i >= suggestLevel(len(_suggestLevel_index)-1) {
		return "suggestLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _suggestLevel_name[_suggestLevel_index[i]:_suggestLevel_index[i+1]]
}
