// Code generated by "stringer -type=typ cipher.go"; DO NOT EDIT.

package shadow

import "strconv"

const _typ_name = "AES_128_GCMAES_192_GCMAES_256_GCMCHACHA20_IETF_POLY1305XCHACHA20_IETF_POLY1305cipherEnd"

var _typ_index = [...]uint8{0, 11, 22, 33, 55, 78, 87}

func (i typ) String() string {
	if i < 0 || i >= typ(len(_typ_index)-1) {
		return "typ(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _typ_name[_typ_index[i]:_typ_index[i+1]]
}
