name: Go
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v7
        with:
          go-version: ^1.26
      - uses: actions/checkout@v7
      - uses: oven-sh/setup-bun@v2

      - name: test and build
        run: |
          make
