// Package web embeds the built admin console frontend into the binary.
// The dist directory is generated by `bun run build` in this directory and
// is committed so `go build` works without a frontend toolchain.
package web

import (
	"embed"
	"fmt"
	"io/fs"
)

//go:embed all:dist
var dist embed.FS

// Dist returns the embedded frontend filesystem rooted at the dist directory.
func Dist() (fs.FS, error) {
	sub, err := fs.Sub(dist, "dist")
	if err != nil {
		return nil, fmt.Errorf("web dist: %w", err)
	}
	return sub, nil
}
